language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql

dist: xenial

sudo: required

before_install:
  - phpenv config-rm xdebug.ini
  - mysql -e 'create database testdibi;'

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit --verbose
